name: EC2 deploy from docker

on:
  push:
    branches: ["QA"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_REPOSITORY: ztencontacto/nodewebapp
  APP_PORT: 5454

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout Code
        uses: actions/checkout@v3

      # Paso 2: Login en el registro Docker
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Construcción y push de la imagen Docker
      - name: Build and Push Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.DOCKER_REPOSITORY }}:latest .
          echo "Pushing Docker image to Docker Registry..."
          docker push ${{ env.DOCKER_REPOSITORY }}:latest
          echo "Docker image built and pushed successfully."

      # Paso 4: Conexión a las instancias EC2 y despliegue
      - name: Deploy to EC2 Instances
        run: |
          echo "Starting deployment to EC2 instances..."
          IFS=',' read -ra HOSTS <<< "${{ secrets.EC2_HOSTS }}"
          APP_NAME=$(basename "${{ env.DOCKER_REPOSITORY }}")
          for HOST in "${HOSTS[@]}"; do
            echo "Deploying to $HOST"
            ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.EC2_KEY }}") ubuntu@$HOST "
              if ! command -v docker &> /dev/null; then
                echo 'Installing Docker...'
                sudo apt update && sudo apt install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
              fi

              echo 'Pulling the latest Docker image...'
              sudo docker pull ${{ env.DOCKER_REPOSITORY }}:latest
              echo 'Stopping any running containers...'
              sudo docker stop $APP_NAME || true
              sudo docker rm $APP_NAME || true
              echo 'Starting new container...'
              sudo docker run -d --name $APP_NAME -p ${{ env.APP_PORT }}:${{ env.APP_PORT }} ${{ env.DOCKER_REPOSITORY }}:latest
            "
            echo "Deployment to $HOST completed."
          done



